application:
    name:        wprecon
    version:     "v2.1.0"
    author:      blackcrw
    description: "WPRecon, is a tool for the recognition of vulnerabilities and blackbox information for wordpress."